# ===================================================================
# SUNUCU VE UYGULAMA AYARLARI
# ===================================================================
spring.application.name=backend
server.port=8080

# ===================================================================
# POSTGRESQL & POSTGIS VER?TABANI BA?LANTI AYARLARI
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/telco_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Otomatik Dialect Yönetimi
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Loglama ve Formatlama Ayarlar?
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===================================================================
# RABBITMQ ENTEGRASYON AYARLARI
# ===================================================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=3000
spring.rabbitmq.template.reply-timeout=3000

# ===================================================================
# MADDE 9: REDIS CACHING AYARLARI
# ===================================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===================================================================
# MADDE 11: SWAGGER / OPENAPI 3 OR?J?NAL YOLLARI (KES?N ÇÖZÜM)
# ===================================================================
# ? Standart rotalara döndük kanka, karma??k iç yönlendirmeler son buldu ?
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operations-sorter=method

# ===================================================================
# JWT GÜVENL?K PARAMETRELER?
# ===================================================================
telco.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
telco.jwt.expiration=86400000